const quizData = [
  {
    id: "1",
    category: "tvd",
    question: `Over the course of the series, which character was NEVER killed by Damon?`,
    choices: [
      { choice: "Alaric Saltzman", isCorrect: false },
      { choice: "Tyler Lockwood", isCorrect: false },
      { choice: "Jeremy Gilbert", isCorrect: false },
      { choice: "Enzo St. John", isCorrect: true },
    ],
  },
  {
    id: "2",
    category: "tvd",
    question: `In that moment, I loved him. I didn't want to, I mean, it terrified me, but for that moment, I loved him.`,
    choices: [
      { choice: "Damon", isCorrect: false },
      { choice: "Elena", isCorrect: true },
      { choice: "Caroline", isCorrect: false },
      { choice: "Stefan", isCorrect: false },
    ],
  },
  {
    id: "3",
    category: "tvd",
    question: `Elena is warm and kind and caring and selfless and it's real. When I'm around her, I completely forget where I am!`,
    choices: [
      { choice: "Damon", isCorrect: false },
      { choice: "Matt", isCorrect: false },
      { choice: "Caroline", isCorrect: false },
      { choice: "Stefan", isCorrect: true },
    ],
  },
  {
    id: "4",
    category: "tvd",
    question: `Which Song Was Reused In Season 5 When Elena Was Trying To Get Stefan To Remember Who He Was?`,
    choices: [
      { choice: "Longest Night", isCorrect: true },
      { choice: "Losing Your Memory", isCorrect: false },
      { choice: "Give Me Love", isCorrect: false },
      { choice: "A Drop In The Ocean", isCorrect: false },
    ],
  },
  {
    id: "5",
    category: "tvd",
    question: ` Where did Caroline and Stefan get married?`,
    choices: [
      { choice: "The Mystic Grill", isCorrect: false },
      { choice: "The Salvatore Boarding House", isCorrect: false },
      { choice: "The Town Square", isCorrect: false },
      { choice: "The Lockwood Mansion", isCorrect: true },
    ],
  },
  {
    id: "6",
    category: "tvd",
    question: `In season 2, how did Bonnie incapacitate Mason?`,
    choices: [
      { choice: "She stabbed him with a silver knife.", isCorrect: false },
      { choice: "She shot him with a silver bullet.", isCorrect: false },
      { choice: "By giving him an aneurysm", isCorrect: true },
      { choice: "She stole the moonstone from Mason", isCorrect: false },
    ],
  },
  {
    id: "7",
    category: "tvd",
    question: `And something tells me that my witch is better than your witch.`,
    choices: [
      { choice: "Katherine", isCorrect: true },
      { choice: "Damon", isCorrect: false },
      { choice: "Elijah", isCorrect: false },
      { choice: "Klaus", isCorrect: false },
    ],
  },
  {
    id: "8",
    category: "tvd",
    question: `Who says this quote; "I have been in love. It's painful, pointless and overrated"?`,
    choices: [
      { choice: "Katherine", isCorrect: false },
      { choice: "Damon", isCorrect: true },
      { choice: "Stefan", isCorrect: false },
      { choice: "Klaus", isCorrect: false },
    ],
  },
  {
    id: "9",
    category: "tvd",
    question: `When Damon and Bonnie are trapped in the prison world with Kai Parker, the same day keeps repeating over and over. What is the date?`,
    choices: [
      { choice: "April 10,1984", isCorrect: false },
      { choice: "April 10,1994", isCorrect: false },
      { choice: "May 10,1994", isCorrect: true },
      { choice: "May 10,1984", isCorrect: false },
    ],
  },
  {
    id: "10",
    category: "tvd",
    question: ` He’s your first love. I intend to be your last, however long it takes`,
    choices: [
      { choice: "Elijah", isCorrect: false },
      { choice: "Damon", isCorrect: false },
      { choice: "Stefan", isCorrect: false },
      { choice: "Klaus", isCorrect: true },
    ],
  },
  {
    id: "11",
    category: "originals",
    question: `What did the Mikaelson family swear to themselves?`,
    choices: [
      { choice: "Love is Power", isCorrect: false },
      { choice: "Family is power", isCorrect: true },
      { choice: "Friendship is power", isCorrect: false },
      { choice: "Vampirism is power", isCorrect: false },
    ],
  },
  {
    id: "12",
    category: "originals",
    question: `What is the weapon that can kill an Original?`,
    choices: [
      { choice: "Silver", isCorrect: false },
      { choice: "White Oak Stake", isCorrect: true },
      { choice: "Dagger", isCorrect: false },
      { choice: "WereWolf Blood", isCorrect: false },
    ],
  },
  {
    id: "13",
    category: "originals",
    question: `How did Klaus first discover that he was a vampire and a werewolf?`,
    choices: [
      { choice: "His mother Esther told him.", isCorrect: false },
      {
        choice: "He activated the werewolf curse after his first kill.",
        isCorrect: true,
      },
      {
        choice:
          "Werewolf daddy came around and whisked them away to be a happy family.",
        isCorrect: false,
      },
      { choice: "He transformed during the full moon.", isCorrect: false },
    ],
  },
  {
    id: "14",
    category: "originals",
    question: `What were the names of the Harvest Girls?`,
    choices: [
      { choice: " Sophie, Agnes, Eva and Davina", isCorrect: false },
      { choice: "Regina, Gretchen, Karen, and Davina", isCorrect: false },
      { choice: "Monique, Cassie, Abigail, and Davina", isCorrect: true },
      { choice: "Victoria, Melanie, Geri, and Davina", isCorrect: false },
    ],
  },
  {
    id: "15",
    category: "originals",
    question: `What were Hayley’s parting words to her deceased husband Jackson?`,
    choices: [
      { choice: "You’re the wolf who’s been watching me.", isCorrect: false },
      { choice: "Till death do us part.", isCorrect: true },
      {
        choice: "I promise you. I will make all of them suffer.",
        isCorrect: false,
      },
      { choice: "To be your family.", isCorrect: false },
    ],
  },
  {
    id: "16",
    category: "originals",
    question: `Which dark object was not used against Klaus?`,
    choices: [
      { choice: "The Rosary of Madness", isCorrect: true },
      { choice: "Papa Tunde’s Blade", isCorrect: false },
      { choice: "The Golden Dagger", isCorrect: false },
      { choice: "White Oak Stake", isCorrect: false },
    ],
  },
  {
    id: "17",
    category: "originals",
    question: `Who was the Wooden Knight originally intended for?`,
    choices: [
      { choice: "Rebekah", isCorrect: false },
      { choice: " Esther", isCorrect: false },
      { choice: "Elijah", isCorrect: false },
      { choice: "Mikael", isCorrect: true },
    ],
  },
  {
    id: "18",
    category: "originals",
    question: `Which of these places does NOT appear on the show?`,
    choices: [
      { choice: "The Abattoir", isCorrect: false },
      { choice: " St. Anne’s Church", isCorrect: false },
      { choice: "Rolling Hills Asylum", isCorrect: true },
      { choice: "Rousseau’s", isCorrect: false },
    ],
  },
  {
    id: "19",
    category: "originals",
    question: `Which dark object trapped Tristan? `,
    choices: [
      { choice: "The Devil’s Star", isCorrect: false },
      { choice: " The Cursed Shackles", isCorrect: false },
      { choice: "The Serratura", isCorrect: true },
      { choice: "Needle of Sorrows", isCorrect: false },
    ],
  },
  {
    id: "20",
    category: "originals",
    question: `How many times has Klaus killed Mikael?`,
    choices: [
      { choice: "One", isCorrect: false },
      { choice: " Two", isCorrect: true },
      { choice: "Three", isCorrect: false },
      { choice: "Too many times to count", isCorrect: false },
    ],
  },
  {
    id: "21",
    category: "legacies",
    question: ` What Is The Name Of The School Where The Legacies Attend?`,
    choices: [
      {
        choice: "The Saltzman Boarding School For The Young & Gifted",
        isCorrect: false,
      },
      {
        choice: "The Salvatore Boarding School For The Young & Talented",
        isCorrect: true,
      },
      {
        choice: "The Saltzman Boarding School For The Young & Talented",
        isCorrect: false,
      },
      {
        choice: "The Salvatore Boarding School For The Young & Gifted",
        isCorrect: false,
      },
    ],
  },
  {
    id: "22",
    category: "legacies",
    question: ` You have such a big heart. It’s okay to let other people see it`,
    choices: [
      { choice: "Emma", isCorrect: false },
      { choice: "Dorian", isCorrect: false },
      { choice: "Jo", isCorrect: true },
      { choice: "Alaric", isCorrect: false },
    ],
  },
  {
    id: "23",
    category: "legacies",
    question: `I care too much. It’s kind of a problem`,
    choices: [
      { choice: "Lizzie", isCorrect: false },
      { choice: "Josie", isCorrect: true },
      { choice: "Hope", isCorrect: false },
      { choice: "Landon", isCorrect: false },
    ],
  },
  {
    id: "24",
    category: "legacies",
    question: `For one, rules are meant to be broken. For two, I am an equal opportunity evil temptress`,
    choices: [
      { choice: "Lizzie", isCorrect: false },
      { choice: "Josie", isCorrect: false },
      { choice: "Penelope", isCorrect: true },
      { choice: "Hope", isCorrect: false },
    ],
  },
  {
    id: "25",
    category: "legacies",
    question: `Which of these monsters was the first one to attack the Salvatore school ?`,
    choices: [
      { choice: "Gargoyle", isCorrect: true },
      { choice: "A monsterous spider", isCorrect: false },
      { choice: "A huge wolf", isCorrect: false },
      { choice: "A dragon", isCorrect: false },
    ],
  },
  {
    id: "26",
    category: "legacies",
    question: `How is Dorian connected to Stefan Salvatore?`,
    choices: [
      { choice: "Dorian's life was saved by Stefan", isCorrect: false },
      { choice: "Dorian's family was killed by Stefan", isCorrect: true },
      { choice: "They are relatives", isCorrect: false },
      { choice: "Dorian is part of his sire line", isCorrect: false },
    ],
  },
  {
    id: "27",
    category: "legacies",
    question: `Killing which of these activated Hope’s werewolf qualities ?`,
    choices: [
      { choice: "Declan, her mother's boyfriend", isCorrect: true },
      { choice: "A man called Bill", isCorrect: false },
      { choice: "Davina Claire", isCorrect: false },
      { choice: "Landon, a student of the Salvatore School", isCorrect: false },
    ],
  },
  {
    id: "28",
    category: "legacies",
    question: `What species is Malivore?`,
    choices: [
      { choice: "Demon", isCorrect: false },
      { choice: "Golem", isCorrect: true },
      { choice: "Vampire", isCorrect: false },
      { choice: "Werewolf", isCorrect: false },
    ],
  },
  {
    id: "29",
    category: "legacies",
    question: `Who is Landon’s mother?`,
    choices: [
      { choice: "Yasmin", isCorrect: false },
      { choice: "Alaina", isCorrect: false },
      { choice: "Yara", isCorrect: false },
      { choice: "Seylah", isCorrect: true },
    ],
  },
  {
    id: "30",
    category: "legacies",
    question: `Why did Lizzie get paralyzed?`,
    choices: [
      { choice: "She got bit by a spider", isCorrect: true },
      { choice: "She got attacked by a vampire", isCorrect: false },
      { choice: "She got injured by a warewolf", isCorrect: false },
      { choice: "She got scratched by gargoyle", isCorrect: false },
    ],
  },
  {
    id: "31",
    category: "teenwolf",
    question: `What Was Stiles Stilinksi's Real Name?`,
    choices: [
      { choice: "Stanis", isCorrect: false },
      { choice: "Mieczyslaw", isCorrect: true },
      { choice: "Cuauhtemoc", isCorrect: false },
      { choice: "Aristoteles", isCorrect: false },
    ],
  },
  {
    id: "32",
    category: "teenwolf",
    question: `In the deadpool, how much is Jordan Parrish worth?`,
    choices: [
      { choice: "$5 million", isCorrect: true },
      { choice: "$10 million", isCorrect: false },
      { choice: "$15 million", isCorrect: false },
      { choice: "$25 million", isCorrect: false },
    ],
  },
  {
    id: "33",
    category: "teenwolf",
    question: `What was the name of mental asylum in Beacon Hills?`,
    choices: [
      { choice: "Lichen House", isCorrect: false },
      { choice: "Eichen House", isCorrect: true },
      { choice: "Hale House", isCorrect: false },
      { choice: "Salcombe Home", isCorrect: false },
    ],
  },
  {
    id: "34",
    category: "teenwolf",
    question: `Who said “Life Can’t Ever Be All Bad Or All Good. You Know, Eventually, Things Have To Come Back To The Middle.” `,
    choices: [
      { choice: "Stiles", isCorrect: false },
      { choice: "Noah", isCorrect: false },
      { choice: "Lydia", isCorrect: false },
      { choice: "Scott", isCorrect: true },
    ],
  },
  {
    id: "35",
    category: "teenwolf",
    question: `Who said “Even When A Leader Thinks They Have Nothing Left To Give, There’s Still One Thing: Hope. Give Them Hope.” `,
    choices: [
      { choice: "Stiles", isCorrect: false },
      { choice: "Noah", isCorrect: false },
      { choice: "Melissa", isCorrect: true },
      { choice: "Rafael", isCorrect: false },
    ],
  },
  {
    id: "36",
    category: "teenwolf",
    question: `Who said “There’s No Such Thing As Fate.” `,
    choices: [
      { choice: "Allison", isCorrect: true },
      { choice: "Stiles", isCorrect: false },
      { choice: "Lydia", isCorrect: false },
      { choice: "Derek", isCorrect: false },
    ],
  },
  {
    id: "37",
    category: "teenwolf",
    question: `Melissa McCall, under the guidance of Chris Argent, gathers the Nine Herbs in order heal the injuries sustained by the latter. What is the binding agent that Chris refers to as “Mil”?” `,
    choices: [
      { choice: "Oil", isCorrect: false },
      { choice: "Water", isCorrect: false },
      { choice: "Soda", isCorrect: false },
      { choice: "Honey", isCorrect: true },
    ],
  },
  {
    id: "38",
    category: "teenwolf",
    question: `Who said it: “I’m A Fan Of Ignoring A Problem Until It Just Goes Away!” `,
    choices: [
      { choice: "Allison", isCorrect: false },
      { choice: "Lydia", isCorrect: false },
      { choice: "Stiles", isCorrect: true },
      { choice: "Derek", isCorrect: false },
    ],
  },
  {
    id: "39",
    category: "teenwolf",
    question: `Where do Kira, Malia, Scott and Stiles quarantine themselves to protect the other students from shapeshifters?`,
    choices: [
      { choice: "Eichen House", isCorrect: false },
      { choice: "The Hale Vault", isCorrect: true },
      { choice: "Beacon Hills Animal Clinic", isCorrect: false },
      { choice: "Beacon Hills High School", isCorrect: false },
    ],
  },
  {
    id: "40",
    category: "teenwolf",
    question: `What is the name of the first episode?`,
    choices: [
      { choice: "Lunar Eclipse", isCorrect: false },
      { choice: "Full Moon", isCorrect: false },
      { choice: "The Bite", isCorrect: false },
      { choice: "Wolf Moon", isCorrect: true },
    ],
  },
  {
    id: "41",
    category: "twilight",
    question: `What instrument does Edward play?`,
    choices: [
      { choice: "Piano", isCorrect: true },
      { choice: "Violin", isCorrect: false },
      { choice: "Drums", isCorrect: false },
      { choice: "Guitar", isCorrect: false },
    ],
  },
  {
    id: "42",
    category: "twilight",
    question: `Which vampire was NOT turned by Carlisle Cullen?`,
    choices: [
      { choice: "Edward", isCorrect: false },
      { choice: "Esme", isCorrect: false },
      { choice: "Rosalie", isCorrect: false },
      { choice: "Jasper", isCorrect: true },
    ],
  },
  {
    id: "43",
    category: "twilight",
    question: `Which Muse song plays during the iconic Twilight baseball scene?`,
    choices: [
      { choice: "Supermassive BlackHole", isCorrect: true },
      { choice: "Time is Running Out", isCorrect: false },
      { choice: "Uprising", isCorrect: false },
      { choice: "Muscle Musium", isCorrect: false },
    ],
  },
  {
    id: "44",
    category: "twilight",
    question: `According to the books, who did James meet first?`,
    choices: [
      { choice: "Edward", isCorrect: false },
      { choice: "Bella", isCorrect: false },
      { choice: "Carlisle", isCorrect: false },
      { choice: "Alice", isCorrect: true },
    ],
  },
  {
    id: "45",
    category: "twilight",
    question: `Who killed Bree Tanner?`,
    choices: [
      { choice: "Jasper", isCorrect: false },
      { choice: "Aro", isCorrect: false },
      { choice: "Felix", isCorrect: true },
      { choice: "Jane", isCorrect: false },
    ],
  },
  {
    id: "46",
    category: "twilight",
    question: `What car did Edward buy Bella after her truck broke down?`,
    choices: [
      { choice: "A Silver Volvo", isCorrect: false },
      { choice: "A Ferrari F430", isCorrect: false },
      { choice: "A BMW M3", isCorrect: false },
      { choice: "A Mercedes Gaurdian", isCorrect: true },
    ],
  },
  {
    id: "47",
    category: "twilight",
    question: `According to Breaking Dawn, how many chromosomes does a vampire have?`,
    choices: [
      { choice: "24", isCorrect: false },
      { choice: "25", isCorrect: true },
      { choice: "26", isCorrect: false },
      { choice: "27", isCorrect: false },
    ],
  },
  {
    id: "48",
    category: "twilight",
    question: `Who was the youngest vampire in the Cullen clan (before Bella turned)?`,
    choices: [
      { choice: "Emmett", isCorrect: true },
      { choice: "Alice", isCorrect: false },
      { choice: "Esme", isCorrect: false },
      { choice: "Rosalie", isCorrect: false },
    ],
  },
  {
    id: "49",
    category: "twilight",
    question: `Who drove the van that almost hits Bella?`,
    choices: [
      { choice: "Mike", isCorrect: false },
      { choice: "Eric", isCorrect: false },
      { choice: "Quil", isCorrect: false },
      { choice: "Tyler", isCorrect: true },
    ],
  },
  {
    id: "50",
    category: "twilight",
    question: `When Jacob Black became the Alpha of his own pack, who became his Beta, or the second-in-command?`,
    choices: [
      { choice: "Quil", isCorrect: false },
      { choice: "Seth", isCorrect: false },
      { choice: "Leah", isCorrect: true },
      { choice: "Embry", isCorrect: false },
    ],
  },
];

export default quizData;
