const discoverData = [
  {
    id: 1,
    title: "Vampires",
    intro: `Vampire, also spelled vampyre, in popular legend, a creature, often fanged, that preys upon humans, generally by consuming their blood. Vampires have been featured in folklore and fiction of various cultures for hundreds of years, predominantly in Europe, although belief in them has waned in modern times. `,
    char: `Because there is a long history of walking corpses and bloodsucking ghouls in folklore, it is difficult to pin down a distinct set of characteristics consistently attributed only to vampires. Central to vampire myth, however, is the consumption of human blood or other essence (such as bodily fluids or psychic energy), followed closely by the possession of sharp teeth or fangs with which to facilitate this task. In most depictions, vampires are “undead”—that is to say, having been somehow revived after death—and many are said to rise nightly from their graves or coffins, often necessarily containing their native soil. Vampires are typically said to be of pale skin and range in appearance from grotesque to preternaturally beautiful, depending on the tale. Another frequently cited physical characteristic is the inability to cast a reflection or shadow, which often translates into an inability to be photographed or recorded on film.`,
    howToConvert: `A person may become a vampire in a variety of ways, the most common of which is to be bitten by a vampire. Other methods include sorcery, committing suicide, contagion, or having a cat jump over a person’s corpse. Some people believed that babies born with teeth or on Christmas or between Christmas and Epiphany were predisposed to becoming vampires. While vampires usually do not die of disease or other normal human afflictions, and they are indeed often said to have faster-than-normal healing capabilities, there are various methods for their destruction. The most popular of those include a wooden stake through the heart, fire, decapitation, and exposure to sunlight. In some stories vampires may enter a home only if they have been invited, and in others they may be distracted by the scattering of objects such as seeds or grains that they are compelled to count, thereby enabling potential victims to escape.`,
  },
  {
    id: 2,
    title: "WereWolves",
    intro: `Werewolf, in European folklore, a man who turns into a wolf at night and devours animals, people, or corpses but returns to human form by day. Some werewolves change shape at will; others, in whom the condition is hereditary or acquired by having been bitten by a werewolf, change shape involuntarily, under the influence of a full moon. If he is wounded in wolf form, the wounds will show in his human form and may lead to his detection. Belief in werewolves is found throughout the world. The psychiatric condition in which a person believes he is a wolf is called lycanthropy. `,
    char: `In addition to the natural characteristics inherent to both wolves and humans, werewolves are often attributed strength and speed far beyond those of wolves or men. The werewolf is generally held as a European character, although its lore spread through the world in later times. Shape-shifters similar to werewolves are common in tales from all over the world.`,
    howToConvert: `Various methods for becoming a werewolf have been reported, one of the simplest being the removal of clothing and putting on a belt made of wolf skin, probably as a substitute for the assumption of an entire animal skin (which also is frequently described). In other cases, the body is rubbed with a magic salve. Drinking rainwater out of the footprint of the animal in question or from certain enchanted streams were also considered effectual modes of accomplishing metamorphosis. The 16th century Swedish writer Olaus Magnus says that the Livonian werewolves were initiated by draining a cup of specially prepared beer and repeating a set formula. Ralston in his Songs of the Russian People gives the form of incantation still familiar in Russia.In Italy, France and Germany, it was said that a man or woman could turn into a werewolf if he or she, on a certain Wednesday or Friday, slept outside on a summer night with the full moon shining directly on his face.Becoming a werewolf simply by being bitten or scratched by another werewolf as a form of contagion is common in modern horror fiction, but this kind of transmission is rare in legend, unlike the case in vampirism.`,
  },

  {
    id: 3,
    title: "Witch",
    intro: `Witches and wizards are people thought to possess magical powers or to command supernatural forces. They appear in the myths and folktales of many cultures. The word “witch” usually refers to a female, though male witches exist in some traditions. Men who possess the powers associated with witchcraft are often known as wizards or warlocks.`,
    char: `They dress a little gaudier, or in more archaic or odd styles, than others do. They wear a lot of jewelry - rings, pendants, earrings - made of natural materials, including leather, wood, and colourful stones, and often having symbols with magical symbols (faces, animals, runes, etc.) or patterns (Celtic knotwork, tribal, aboriginal or Native American) and have magical items “hiding in plain sight” in their personal spaces (home, office, vehicles) such as crystals, candles, tumbled stones, spheres, wall hangings, and stars.`,
    howToConvert: `There’s a few ways to do so. Many Wiccans prefer to ritualize it, meaning to make it a ritual in and of itself.Rituals are often full of symbolism. Christianity’s baptism is like this, actually. To be washed in the water/oils of baptism is to die and be born again. This is the origin of some of the philosophies that formed the “Born-Again Christian” movement.A dedication ritual to become a full Wiccan can involve a candle or even a dandelion. It can involve rings, incense, stones-whatever it can be. Think of what it means to you to become a Wiccan, what you hope for it. Send your thoughts out in one way or another. Make your dedication meaningful with that message. Consider how to make that message manifest through symbols. Wish upon a dandelion’s full head of seeds. Scatter rocks into the local body of water. Bury a ring in a flower pot and plant some seeds. Those are some ideas of what it could be.The next part’s harder: now study. Traditionally, for a year and a day. Learn what the practice is, learn the holidays and what they mean. Begin to make room in your life for Wicca and invite it in. Make a robe for rituals. Create a book of shadows to go over what you’ve learned and experienced in your journey. Seek out books and a coven if you can find one.`,
  },
  {
    id: 4,
    title: "Banshee",
    intro: `Banshees are human in appearance, and, unlike most supernatural creatures, they do not possess the power to shapeshift. They also do not have superhuman physical attributes such as super strength or accelerated healing, which gives them the same form of mortality as a regular human as well. Banshees are not actually true supernatural creatures who are controlled by the moon or other mystical forces such as Werewolves and Hellhounds; instead, they are humans with access to the supernatural, allowing the aforementioned mystical forces to flow through them so the Banshee can utilize the powers these forces create.The ears of a Banshee are naturally tuned to levels of the universe that only they can hear. This gives them an ability to discern details of a person's death (or impending death) through the sounds they can perceive which no one else can. These sounds can include voices (such as whispering or screaming), gunshots, electricity, buzzing, growling, fighting, etc.`,
    char: `Banshees can be benevolent or malevolent creatures. Banshees tied to fairy lore are known to cry out as a warning to a person's impending death. Malevolent banshees appear as females with dark flowing hair, pale skin, and sunken eyes, dressed in blood-red robes.They’re always cold. Mysteriously so.Their singing voice is best described as “the blood-curdling yowl of a helldemon”.They can travel through mist, allowing them entry into most places.Banshees can use telekinesis to subdue their victims.`,
    howToConvert: `The Banshee trait is known to be inherited by the females of a bloodline. Their supernatural powers areactivated upon reaching adulthood though extremely traumatic events can trigger these nascent abilities at an earlier age.Banshee heritage can also be triggered by a traumatic event such as werewolf,vampire bite`,
  },
  {
    id: 5,
    title: "Oni",
    intro: `Oni also pronounced as ki- as a prefix (meaning "hidden, supernatural, fierce, wrathful") also known as kijin (fierce person,demonic spirit) variously translates as: (Ogre, troll, fiend, demon, daemon, devil, evil spirit) are monstrous horned humanoids who are found in countless Japanese stories and myths. They tend to be the enemies of mankind and are generally depicted as roguish villains.`,
    char: `Oni are one of the most well-known icons of Japanese folklore. They are large and scary, standing taller than the tallest man, and sometimes many times that. They come in many varieties but are most commonly depicted with red or blue skin, wild hair, two or more horns, and fang-like tusks.Other variations exist in different colors and with different numbers of horns, eyes, or fingers and toes. They wear loincloths made of the pelts of great beasts.`,
    howToConvert: `Oni are born when truly wicked humans die and end up in one of the many Buddhist Hells, transformed into Oni. They become the ogreish and brutal servants of Great Lord Enma, ruler of Hell, wielding iron clubs with which they crush and destroy humans solely for enjoyment. An oni’s job is to mete out horrible punishments such as peeling off skin, crushing bones, and other torments too horrible to describe to those who were wicked (but not quite wicked enough to be reborn as demons themselves). Hell is full of oni, and they make up the armies of the great generals of the underworld.Occasionally, when a human is so utterly wicked that his soul is beyond any redemption, he transforms into an oni during life, and remains on Earth to terrorize the living. These transformed oni are the ones most legends tell about, and the ones who pose the most danger to humankind.All oni possess extreme strength and constitution, and many of them are also accomplished sorcerers. They are ferocious demons, bringers of disaster, spreaders of disease, and punishers of the damned in Hell.`,
  },
  {
    id: 6,
    title: "Phoenix",
    intro: `Phoenix is a mythical bird with colorful feathers and a tail of gold and scarlet. In the ancient Greek and Egyptian mythologies, it is described as a large bird, much like an eagle, with supernatural powers to come back to life. The appearance of this bird has been described differently in different cultures but everywhere, the phoenix bird is looked upon as a symbol of immortality, rebirth and life after death. Descriptions of the Phoenix include its lifespan described in thousands of years and its end by building a huge stick nest and consuming itself in flames only to rise again from the ashes. It has become a symbol of rebirth across many cultures worldwide dating likely from the beginnings of recorded history well into the present. `,
    char: `Phoenixes have the ability to resurrect from the dead. The body will spontaneously self-combust only for the phoenix to be reborn from the ashes, fully restored. It is unknown whether or not if there is a limited number of times a phoenix can resurrect before they perish permanently. Furthermore, there does not seem to be a set amount of time that it takes for a phoenix to resurrect.Phoenixes seemingly possess some form of levitation - allowing them to float a few feet up off the ground.Phoenixes can produce wings of fire from their backs that enable them to fly.`,
    howToConvert: `Associated with the sun, a phoenix obtains new life by arising from the ashes of its predecessor. Some legends say it dies in a show of flames and combustion, others that it simply dies and decomposes before being born again.`,
  },
  {
    id: 7,
    title: "Dragon",
    intro: `Dragon, in the mythologies, legends, and folktales of various cultures, a large lizard- or serpent-like creature, conceived in some traditions as evil and in others as beneficent. In medieval Europe, dragons were usually depicted with wings and a barbed tail and as breathing fire. In Greece the word drakōn, from which the English word was derived, was used originally for any large serpent (see sea serpent), and the dragon of mythology, whatever shape it later assumed, remained essentially a snake.`,
    char: `The dragon’s form varied from the earliest times. The Chaldean dragon Tiamat had four legs, a scaly body, and wings, whereas the biblical dragon of Revelation, “the old serpent,” was many-headed like the Greek Hydra. Because they not only possessed both protective and terror-inspiring qualities but also had decorative effigies, dragons were early used as warlike emblems.In East Asian mythologies the dragon retains its prestige and is conceived as a beneficent creature. The Chinese dragon, lung, represents yang, the principle of heaven, activity, and maleness in the yinyang of Chinese cosmology. `,
    howToConvert: `Turning into a real reptilian dragon is somewhat complicated as it is a very high level and complex magic and even great wizards and shapeshifters try to turn but seldom succeed (even I am trying it).On the other hand, being a draconimus requires for your past life to be as a draconian. Draconians are alien beings that hail from the Alpha-Draconis Star System, many draconians that died during the previous reptilian wars have been reincarnated on Earth, so you do have a good chance (like me). However, draconimi have many traits you don’t see in humans like scaly skin, lizardly eyes and heat resistance (these are some of the qualities I have so I don’t know about others).`,
  },
  {
    id: 8,
    title: "Zombie",
    intro: `Zombie is a will-less and speechless human (as in Voodoo belief and in fictional stories) held to have died and been supernaturally reanimated.The supernatural power that according to voodoo belief may enter into and reanimate a dead body.
Or a person held to resemble the so-called walking dead. `,
    char: `Although the word zombie has been applied to different types of creatures, they generally share a few defining characteristics, perhaps most importantly a lack of free will. Zombies are usually wholly subordinate, either to an outside force, such as a sorcerer, or to an overwhelming desire, such as the need for human flesh or revenge or simply to do violence. Another important distinction made by some is that a zombie is the animated corpse of a single being, usually a human. Zombies are frequently depicted as shambling and rotting, although in some instances their bodies may be preserved, especially when magic is involved, and they may sometimes display superhuman characteristics, such as increased strength and speed.`,
    howToConvert: `Zombies may be created in a variety of ways. Early depictions, drawing from Haitian Vodou, often represented witchcraft as a means for reviving corpses. Haitian zombi are said to be created by maleficent priests or sorcerers for the purpose of doing their bidding. There are two potential parts to the Vodou process: first, a zombi astral is created by removing part of a person’s soul. Then this part of the soul may be used for further magic, including the revivification of the person’s corpse, or zombi corps cadavre. Methods of zombification developed in fiction include radiation exposure and contagion. Especially noteworthy in the latter case is the danger of a so-called “zombie apocalypse,” in which the eventual zombification of the human population through virulence seems inevitable. Zombies are often depicted as proliferating by killing or infecting others—usually by biting—who then become zombies themselves.`,
  },
  {
    id: 9,
    title: "Mermaid",
    intro: `Mermaid, masculine merman, a fabled marine creature with the head and upper body of a human being and the tail of a fish. Similar divine or semidivine beings appear in ancient mythologies (e.g., the Chaldean sea god Ea, or Oannes). In European folklore, mermaids (sometimes called sirens) and mermen were natural beings who, like fairies, had magical and prophetic powers. They loved music and often sang. Though very long-lived, they were mortal and had no souls.`,
    char: `The widely known physical characteristics of mermaids are the head and upper body of a female human and the tail of a fish. The social characteristics differ from one culture to another. Mermaids are commonly found in the open ocean but they also swim to freshwater lakes and rivers.These headstrong creatures crave the freedom that the sea provides, swimming where they please, whenever they choose. Their fierce independence and refusal to conform are combined with a headstrong personality. Mermaids hold steadfastly to their values and won't compromise when it comes to how they live their lives`,
    howToConvert: `Many of us fall asleep dreaming about being a mermaid and exploring the ocean as if it were our natural habitat. There are hundreds of legends about mermaids and sirens around the globe, and it’s easy to understand why. The ancient Greeks believed in the god Atargatis, who had the body of a fish and head of a human. Since ships first set sail, sailors have been tempted by sirens. Even Chinese mythology has tales of mermaids who cried tears that would turn into pearls. But acoording to research there is no assure way to become one`,
  },
  {
    id: 10,
    title: "Goblin",
    intro: `A Goblin (alt. spellings: gobbelin, gobblin, goblyn, gobling, gobelin) is a mischievous, and usually very unpleasant, vengeful, and greedy creature whose primary purpose is to cause trouble to humankind; this is the most common type according to European folklore. There is a smaller population of Goblins, however, that possess a kinder, or more neutral temperament. Regardless of the type, though, all Goblins are rumored to hold various kinds of special abilities, often magical in nature. Some Goblins possess more fairy-like powers, similar to those of a witch or warlock; other types of Goblin have more demonic abilities, only using their magic to do harm.`,
    char: `The appearance of a Goblin varies quite dramatically depending on its country of origin, although most types of Goblin are known for having quite unruly hair and green-colored skin. What many people don’t know is that there are actually 10 different types of Goblin; these types are often referred to as “sub-races” and each sub-race will typically have a distinct appearance and set of abilities. When most people think of a Goblin, what they’re imagining is usually the type known as a Trow or a Kobold. Trows have the ability to morph into human-like form; however, they are usually small in stature with an “ugly” appearance. Kobolds are more the stereotypical Goblin, with an appearance similar to the house-elf known as “Dobby” in the Harry Potter series.They are almost always small and grotesque, mischievous or outright malicious, and greedy, especially for gold and jewelry. They often have magical abilities similar to a fairy or demon. Similar creatures include brownies, dwarfs, duendes, gnomes, imps, and kobolds`,
    howToConvert: `A person can be converted to a goblin by Transfiguration. Transfiguration was a branch of magic that focused on the alteration of the form or appearance of an object, via the alteration of the object's molecular structure. Transfiguration could be done to most (if not all) objects and, as with most forms of magic, it included  but is hardly limited to Transfiguration spells.`,
  },
  {
    id: 11,
    title: "Windigo",
    intro: `Windigo is a a cannibalistic creature of Algonquian mythology believed to have been a lost hunter forced by hunger to eat human flesh and thereafter to have become a crazed man-eating ogre roaming the forest. In addition to inaccurate imagery, popular depictions of the windigo as a ravenous animal have also displaced the original emphasis that Indigenous people placed on the windigo as a lesson on human greed. These narratives also fail to acknowledge that the windigo, and the Indigenous cultures that imagined it, have evolved over time, as have Indigenous peoples’ cultural practices. Smallman notes that current images of the windigo separate it  “from Aboriginal culture, in that there is little meaningful discussion of Native beliefs. Instead, Aboriginal peoples are often associated with a simplified version of the past, in which discussions of colonialism are avoided.`,
    char: `The Wendigo appearance varies on several levels to many people, most see them as 10 foot tall demons with an enormous heads, gigantic teeth inside twisted mouths, and beady eyes. Others say the windigo has either no fur at all, or snow white fur, often blood stained or matted, bloody hair, with a grotesque maw filled with sharp, yellow fangs, it's hands and feet end in razor-sharp talons, with twisted lips that are feckled with blood, and their tongues are a disgusting dark blue.`,
    howToConvert: `In most versions of the legend, a human becomes a windigo after his or her spirit is corrupted by greed or weakened by extreme conditions, such as hunger and cold. In other legends, humans become windigos when possessed by a prowling spirit during a moment of weakness.`,
  },
  {
    id: 12,
    title: "Cyclops",
    intro: `The Cyclops ("round eyes") are strong, one-eyed giants in Greek mythology, who helped Zeus defeat the Titans and hindered Odysseus from getting home on time.According to the story told in the "Theogony" of the Greek epic poet Hesiod, the Cyclops were the sons of Uranus (Sky) and Gaia (Earth). The Titans and Hekatoncheiries (or Hundred-handers), both known for their size, were also said to have been the offspring of Uranus and Gaia. Uranus kept all of his children imprisoned inside their mother Gaia and when the Titan Cronus decided to help his mother by overthrowing Uranus, the Cyclops helped. But instead of rewarding them for their assistance, Cronus imprisoned them in Tartarus, the Greek Underworld.According to Hesiod, there were three Cyclopes, known as Argos ("Vividly Bright"), Steropes ("Lightning Man"), and Brontes ("Thunder Man"), and they were skilled and powerful blacksmiths—in later tales they are said to have assisted the smith-god Hephaistos in his forge under Mt. Etna. These workmen are credited with creating thunderbolts, the weapons used by Zeus to defeat the Titans, and they are also thought to have made the altar at which Zeus and his allies swore allegiance before that war.`,
    char: `Cyclopes are massive, lumbering beasts, so tall that a grown man would still fall below their knees. They have block-shaped heads with broad features and a single, round eye in the center of the forehead, right above the nose.On top of their naturally crude appearance, these creatures make no effort to look civilized. They allow their hair and beards to grow into tangled masses, wear rough clothing made from animal skins, and hardly ever bathe.`,
    howToConvert: ` A condition called cyclopia may have been brought on by the use of white hellebore, a dangerous mutagen which the Greeks mistook for a medical herb. Children born with cyclopia have a conjoined eye beneath their nose, which would certainly alarm any Greek person. However, cases of cyclopia, even when the mother is exposed to white hellebore, are very rare, and the children rarely live past infancy, making it unlikely that they would be connected with a giant race of monstrous strength.`,
  },
];
export default discoverData;
