const shoppingData = [
  {
    id: 1,
    title: `Alison's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/alison1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/alison1-02.png",
    price: 500,
  },
  {
    id: 2,
    title: `Alison's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/alison2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/alison2-02.png",
    price: 455,
  },
  {
    id: 3,
    title: `Alison's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/alison3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/alison3-02.png",
    price: 470,
  },
  {
    id: 4,
    title: `Alison's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/alison4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/alison4-02.png",
    price: 550,
  },
  {
    id: 5,
    title: `Bella's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bella1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bella1-02.png",
    price: 480,
  },
  {
    id: 6,
    title: `Bella's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bella2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bella2-02.png",
    price: 555,
  },
  {
    id: 7,
    title: `Bella's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bella3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bella3-02.png",
    price: 490,
  },
  {
    id: 8,
    title: `Bella's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bella4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bella4-02.png",
    price: 389,
  },
  {
    id: 9,
    title: `Bonnie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bonnie1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bonnie1-02.png",
    price: 500,
  },
  {
    id: 10,
    title: `Bonnie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bonnie2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bonnie2-02.png",
    price: 455,
  },
  {
    id: 11,
    title: `Bonnie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bonnie3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bonnie3-02.png",
    price: 470,
  },
  {
    id: 12,
    title: `Bonnie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/bonnie4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/bonnie4-02.png",
    price: 558,
  },
  {
    id: 13,
    title: `Caroline's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/car1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/car1-02.png",
    price: 474,
  },
  {
    id: 14,
    title: `Caroline's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/car2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/car2-02.png",
    price: 585,
  },
  {
    id: 15,
    title: `Caroline's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/car3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/car3-02.png",
    price: 499,
  },
  {
    id: 16,
    title: `Caroline's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/car4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/car4-02.png",
    price: 337,
  },
  {
    id: 17,
    title: `Elena's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/elena1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/elena1-02.png",
    price: 505,
  },
  {
    id: 18,
    title: `Elena's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/elena2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/elena2-02.png",
    price: 450,
  },
  {
    id: 19,
    title: `Elena's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/elena3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/elena3-02.png",
    price: 476,
  },
  {
    id: 20,
    title: `Elena's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/elena4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/elena4-02.png",
    price: 337,
  },
  {
    id: 21,
    title: `Freya's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/freya1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/freya1-02.png",
    price: 434,
  },
  {
    id: 22,
    title: `Freya's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/freya2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/freya2-02.png",
    price: 323,
  },
  {
    id: 23,
    title: `Freya's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/freya3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/freya3-02.png",
    price: 465,
  },
  {
    id: 24,
    title: `Freya's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/freya4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/freya4-02.png",
    price: 380,
  },
  {
    id: 25,
    title: `Hayley's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hayley1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hayley1-02.png",
    price: 529,
  },
  {
    id: 26,
    title: `Hayley's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hayley2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hayley2-02.png",
    price: 485,
  },
  {
    id: 27,
    title: `Hayley's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hayley3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hayley3-02.png",
    price: 430,
  },
  {
    id: 28,
    title: `Hayley's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hayley4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hayley4-02.png",
    price: 568,
  },
  {
    id: 29,
    title: `Hope's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hope1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hope1-02.png",
    price: 434,
  },
  {
    id: 30,
    title: `Hope's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hope2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hope2-02.png",
    price: 563,
  },
  {
    id: 31,
    title: `Hope's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hope3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hope3-02.png",
    price: 320,
  },
  {
    id: 32,
    title: `Hope's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/hope4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/hope4-02.png",
    price: 364,
  },
  {
    id: 33,
    title: `Jossie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/jossie1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/jossie1-02.png",
    price: 486,
  },
  {
    id: 34,
    title: `Jossie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/jossie2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/jossie2-02.png",
    price: 433,
  },
  {
    id: 35,
    title: `Jossie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/jossie3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/jossie3-02.png",
    price: 333,
  },
  {
    id: 36,
    title: `Jossie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/jossie4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/jossie4-02.png",
    price: 324,
  },
  {
    id: 37,
    title: `Katherine's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kath1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kath1-02.png",
    price: 432,
  },
  {
    id: 38,
    title: `Katherine's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kath2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kath2-02.png",
    price: 476,
  },
  {
    id: 39,
    title: `Katherine's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kath3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kath3-02.png",
    price: 454,
  },
  {
    id: 40,
    title: `Katherine's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kath4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kath4-02.png",
    price: 387,
  },
  {
    id: 41,
    title: `Kira's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kira1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kira1-02.png",
    price: 527,
  },
  {
    id: 42,
    title: `Kira's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kira2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kira2-02.png",
    price: 325,
  },
  {
    id: 43,
    title: `Kira's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kira3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kira3-02.png",
    price: 432,
  },
  {
    id: 44,
    title: `Kira's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/kira4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/kira4-02.png",
    price: 528,
  },
  {
    id: 45,
    title: `Lizzie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lizzie1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lizzie1-02.png",
    price: 427,
  },
  {
    id: 46,
    title: `Lizzie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lizzie2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lizzie2-02.png",
    price: 549,
  },
  {
    id: 47,
    title: `Lizzie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lizzie3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lizzie3-02.png",
    price: 429,
  },
  {
    id: 48,
    title: `Lizzie's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lizzie4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lizzie4-02.png",
    price: 338,
  },
  {
    id: 49,
    title: `Lydia's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lydia1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lydia1-02.png",
    price: 552,
  },
  {
    id: 50,
    title: `Lydia's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lydia2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lydia2-02.png",
    price: 459,
  },
  {
    id: 51,
    title: `Lydia's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lydia3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lydia3-02.png",
    price: 396,
  },
  {
    id: 52,
    title: `Lydia's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/lydia4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/lydia4-02.png",
    price: 371,
  },
  {
    id: 53,
    title: `Rebekah's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/rebekah1-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/rebekah1-02.png",
    price: 419,
  },
  {
    id: 54,
    title: `Rebekah's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/rebekah2-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/rebekah2-02.png",
    price: 321,
  },
  {
    id: 55,
    title: `Rebekah's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/rebekah3-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/rebekah3-02.png",
    price: 462,
  },
  {
    id: 56,
    title: `Rebekah's Top`,
    category: "tops",
    img1: "./images/shopping-images/shopping-cart/tops/rebekah4-01.png",
    img2: "./images/shopping-images/shopping-cart/tops/rebekah4-02.png",
    price: 381,
  },
  {
    id: 57,
    title: `Alison's Skirt`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/alison1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/alison1-02.png",
    price: 555,
  },
  {
    id: 58,
    title: `Caroline's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/car1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/car1-02.png",
    price: 789,
  },
  {
    id: 59,
    title: `Caroline's Skirt`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/car2-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/car2-02.png",
    price: 348,
  },
  {
    id: 60,
    title: `Elena's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/elena1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/elena1-02.png",
    price: 897,
  },
  {
    id: 61,
    title: `Elena's Shorts`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/elena2-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/elena2-02.png",
    price: 666,
  },
  {
    id: 62,
    title: `Friya's Skirt`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/friya1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/friya1-02.png",
    price: 754,
  },
  {
    id: 63,
    title: `Hayley's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/hayley1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/hayley1-02.png",
    price: 951,
  },
  {
    id: 64,
    title: `Kira's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/kira1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/kira1-02.png",
    price: 1204,
  },
  {
    id: 65,
    title: `Kira's Skirt`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/kira2-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/kira2-02.png",
    price: 512,
  },
  {
    id: 66,
    title: `Klaus's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/klaus1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/klaus1-02.png",
    price: 1260,
  },
  {
    id: 67,
    title: `Liv's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/liv1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/liv1-02.png",
    price: 1574,
  },
  {
    id: 68,
    title: `Lydia's Skirt`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/lydia1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/lydia1-02.png",
    price: 870,
  },
  {
    id: 69,
    title: `Malia's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/malia1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/malia1-02.png",
    price: 1103,
  },
  {
    id: 70,
    title: `Malia's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/malia2-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/malia2-02.png",
    price: 823,
  },
  {
    id: 71,
    title: `Malia's Shorts`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/malia3-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/malia3-02.png",
    price: 860,
  },
  {
    id: 72,
    title: `Stefans's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/stefan1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/stefan1-02.png",
    price: 1340,
  },
  {
    id: 73,
    title: `Stiles's Jeans`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/stiles1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/stiles1-02.png",
    price: 986,
  },
  {
    id: 74,
    title: `Carolines's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/car1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/car1-02.png",
    price: 2500,
  },
  {
    id: 75,
    title: `Carolines's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/car2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/car2-02.png",
    price: 2200,
  },
  {
    id: 76,
    title: `Carolines's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/car3-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/car3-02.png",
    price: 2340,
  },
  {
    id: 77,
    title: `Carolines's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/car4-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/car4-02.png",
    price: 1990,
  },
  {
    id: 78,
    title: `Rebekah's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/rebekah1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/rebekah1-02.png",
    price: 1390,
  },
  {
    id: 79,
    title: `Alison's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/alison1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/alison1-02.png",
    price: 800,
  },
  {
    id: 80,
    title: `Alison's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/alison2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/alison2-02.png",
    price: 689,
  },
  {
    id: 81,
    title: `Alison's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/alison3-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/alison3-02.png",
    price: 761,
  },
  {
    id: 82,
    title: `Alison's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/alison4-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/alison4-02.png",
    price: 950,
  },
  {
    id: 83,
    title: `Bella's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/bella1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/bella1-02.png",
    price: 2500,
  },
  {
    id: 84,
    title: `Bella's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/bella2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/bella2-02.png",
    price: 1800,
  },
  {
    id: 85,
    title: `Bella's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/bella3-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/bella3-02.png",
    price: 1789,
  },
  {
    id: 86,
    title: `Bonnie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/bonnie1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/bonnie1-02.png",
    price: 1459,
  },
  {
    id: 87,
    title: `Bonnie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/bonnie2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/bonnie2-02.png",
    price: 999,
  },
  {
    id: 88,
    title: `Bonnie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/bonnie3-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/bonnie3-02.png",
    price: 1679,
  },
  {
    id: 89,
    title: `Bonnie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/bonnie4-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/bonnie4-02.png",
    price: 667,
  },
  {
    id: 90,
    title: `Camila's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/camila1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/camila1-02.png",
    price: 759,
  },
  {
    id: 91,
    title: `Camila's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/camila2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/camila2-02.png",
    price: 761,
  },
  {
    id: 92,
    title: `Camila's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/camila3-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/camila3-02.png",
    price: 952,
  },
  {
    id: 93,
    title: `Camila's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/camila4-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/camila4-02.png",
    price: 800,
  },
  {
    id: 94,
    title: `Devina's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/devina1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/devina1-02.png",
    price: 669,
  },
  {
    id: 95,
    title: `Devina's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/devina2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/devina2-02.png",
    price: 729,
  },
  {
    id: 96,
    title: `Elena's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/elena1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/elena1-02.png",
    price: 2678,
  },
  {
    id: 97,
    title: `Elena's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/elena2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/elena2-02.png",
    price: 1256,
  },
  {
    id: 98,
    title: `Emma's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/emma1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/emma1-02.png",
    price: 987,
  },
  {
    id: 99,
    title: `Friya's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/friya1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/friya1-02.png",
    price: 2100,
  },

  {
    id: 101,
    title: `Friya's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/friya2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/friya2-02.png",
    price: 880,
  },
  {
    id: 102,
    title: `Hope's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/hope1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/hope1-02.png",
    price: 1890,
  },
  {
    id: 103,
    title: `Jossie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/jossie1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/jossie1-02.png",
    price: 1105,
  },
  {
    id: 104,
    title: `Jossie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/jossie2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/jossie2-02.png",
    price: 785,
  },
  {
    id: 105,
    title: `Jossie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/jossie3-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/jossie3-02.png",
    price: 1200,
  },
  {
    id: 106,
    title: `Katherine's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/kath1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/kath1-02.png",
    price: 754,
  },
  {
    id: 107,
    title: `Lizzie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/lizzie1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/lizzie1-02.png",
    price: 1434,
  },
  {
    id: 108,
    title: `Lizzie's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/lizzie2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/lizzie2-02.png",
    price: 600,
  },
  {
    id: 109,
    title: `Lidia's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/lydia1-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/lydia1-02.png",
    price: 655,
  },
  {
    id: 110,
    title: `Lidia's Dress`,
    category: "dresses",
    img1: "./images/shopping-images/shopping-cart/dresses/lydia2-01.png",
    img2: "./images/shopping-images/shopping-cart/dresses/lydia2-02.png",
    price: 678,
  },
  {
    id: 111,
    title: `Katherine's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/kath-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/kath-02.jpg",
    price: 1200,
  },
  {
    id: 112,
    title: `Damon's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/damon-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/damon-02.jpg",
    price: 1675,
  },
  {
    id: 113,
    title: `Edward's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/edward-01.jpg",
    img2: "./images/shopping-images/shopping-cart/jackets/edward-02.jpg",
    price: 2000,
  },
  {
    id: 114,
    title: `Alison's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/alison-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/alison-02.png",
    price: 1250,
  },
  {
    id: 115,
    title: `Bella's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/bella-01.jpg",
    img2: "./images/shopping-images/shopping-cart/jackets/bella-02.jpg",
    price: 1550,
  },
  {
    id: 116,
    title: `Devina's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/devina-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/devina-02.png",
    price: 1435,
  },
  {
    id: 117,
    title: `Jacob's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/jacob-01.jpg",
    img2: "./images/shopping-images/shopping-cart/jackets/jacob-02.jpg",
    price: 1855,
  },
  {
    id: 118,
    title: `Klaus's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/klaus-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/klaus-02.png",
    price: 1300,
  },
  {
    id: 119,
    title: `Lydia's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/lydia-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/lydia-02.png",
    price: 1350,
  },

  {
    id: 120,
    title: `Malia's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/malia-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/malia-02.png",
    price: 1255,
  },
  {
    id: 121,
    title: `Marcel's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/marcel-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/marcel-02.png",
    price: 1375,
  },
  {
    id: 122,
    title: `Rebekah's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/rebekah-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/rebekah-02.jpg",
    price: 1458,
  },
  {
    id: 123,
    title: `Kira's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/kira-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/kira-02.png",
    price: 1400,
  },
  {
    id: 124,
    title: `Hayley's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/hayley-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/hayley-02.png",
    price: 1556,
  },
  {
    id: 125,
    title: `Stiles's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/stiles-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/stiles-02.png",
    price: 1236,
  },
  {
    id: 126,
    title: `Theo's Jacket`,
    category: "jackets",
    img1: "./images/shopping-images/shopping-cart/jackets/theo-01.png",
    img2: "./images/shopping-images/shopping-cart/jackets/theo-02.png",
    price: 1193,
  },
  {
    id: 127,
    title: `Bonnie's Skirt`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/bonnie1-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/bonnie1-02.png",
    price: 786,
  },
  {
    id: 128,
    title: `Elena's Skirt`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/elena3-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/elena3-02.png",
    price: 550,
  },
  {
    id: 129,
    title: `Caroline's Shorts`,
    category: "bottoms",
    img1: "./images/shopping-images/shopping-cart/bottoms/car3-01.png",
    img2: "./images/shopping-images/shopping-cart/bottoms/car3-02.png",
    price: 671,
  },
];

export default shoppingData;
